---

deployment:
tasks:
  - export DEPLOYPATH=/home/phiproje/public_html/portfolio/
  - /bin/cp index.html $DEPLOYPATH
  - /bin/cp -R img $DEPLOYPATH
  - /bin/cp -R css $DEPLOYPATH
  - /bin/cp -R font $DEPLOYPATH
  - /bin/cp -R js $DEPLOYPATH
